import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies();
  const theme = cookieStore.get('theme')?.value || 'dark';
  const common = "h-full w-full";
  return (
    <html lang="en" className={`${theme === "dark" ? "dark": "light"} ${common}`}>
      <body className={`${inter.className} ${common}`}>
        {children}
      </body>
    </html>
  )
}
